### ISSUE TITLE
Can't View Chapters

### ISSUE THREAD

**Issue by corinloch** [sn0w12/Akari#79]
Hi, Thanks for adding the register function. got some another issue, sorry again to disturb

so when I try to point it to a sub domain and configure nginx in order for my friends to type it easily instead of IP: Port and when I try to read any chapters, I encountered this error

```
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 2215079992
```
On Terminal it says this:
```
API Error: Error: SUPABASE_SERVICE_ROLE_KEY is required for this operation
  at c (.next/server/app/api/bookmarks/[id]/route.js:1:5206)
  at t_ (.next/server/app/api/manga/malsync/pdate/route.js:1:61998)
  typerError: fetch failed
  at sync d (.next/server/app/manga-reader)/manga/[id]/[subId]/page.js:1:!23662)
  at sync c (.next/server/app/manga-reader)/manga/[id]/[subId]/page.js:1:!23928)
digeest: '2215079992',
[cause]: [Error {InvalidArgumentError]: invalid connection header} {
   code: 'UND_ERR_INVALID_ARG'
   }
 }
```
But when I tried not using the domain but direct IP: Port everything is working fine , I also did tried fresh reinstalling and same issue still happens, please help, Thanks!

**Comment by sn0w12** [comment]
I think it should be fixed on the dev branch now, could you check?

**Comment by corinloch** [comment]
Still The Same IP works , Domain Not, I pull the latest dev

Here are some pic for reference

Port:IP
![image (2)](https://github.com/user-attachments/assets/b75a62f3-e1b8-489a-b626-2c75f9792f0b)

Domain
![image (3)](https://github.com/user-attachments/assets/aa74756a-7c7f-41ba-bcca-4704a621f26f)

**Comment by sn0w12** [comment]
I think it should be fixed now? It's a bit hard to tell since I cannot replicate the error myself, but I think I might know what was causing it. Could you try again for me?

**Comment by corinloch** [comment]
i pull the latest dev branch, still the same issue persist

**Comment by sn0w12** [comment]
I have tried skipping the connection header when getting the users headers since that seems like what the error is about. Could you try again? Sorry about this.

**Comment by corinloch** [comment]
This issue is now fixed, Thanks for the help!
